import type { NextPage } from "next";
import Head from "next/head";

import Banner from "../components/banner";
import Card from "../components/card";
import cafeData from "../data/coffee-stores.json";

import styles from "../styles/Home.module.css";
import Image from "next/image";

export async function getStaticProps() {
  return {
    props: {
      cafeList: cafeData,
    },
  };
}

interface CafeList {
  id: string;
  address: string;
  imgUrl: string;
  name: string;
  neighbourhood: string;
  websiteUrl: string;
}

interface Props {
  cafeList: CafeList[];
}

const Home: NextPage<Props> = ({ cafeList }) => {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="hero-image"
            width={700}
            height={400}
          />
        </div>
        {cafeList.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Toronto cafe</h2>
            <div className={styles.cardLayout}>
              {cafeList.map((cafe) => (
                <Card
                  key={cafe.id}
                  name={cafe.name}
                  href={`/coffee-store/${cafe.id}`}
                  imgUrl={cafe.imgUrl}
                />
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
