import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/banner";
import Link from "next/link";

import styles from "../styles/Home.module.css";
import Image from "next/image";

const Home: NextPage = () => {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };

  const cafeList = [
    { id: "cafe1", name: "Cafe 1" },
    { id: "cafe2", name: "Cafe 2" },
    { id: "cafe3", name: "Cafe 3" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="hero-image"
            width={700}
            height={400}
          />
        </div>
        {cafeList.map((cafe) => (
          <Link key={cafe.id} href={`/coffee-store/${cafe.id}`}>
            <a>{cafe.name}</a>
          </Link>
        ))}
      </main>
    </div>
  );
};

export default Home;
